In [ ]:
from google.colab import drive
import os
import pandas as pd
from scipy import stats
import numpy as np

In [ ]:
drive.mount('/content/drive')

DATA_DIR = '/content/drive/MyDrive/data'

# 3. Automatically change the working directory so relative paths work
if os.path.exists(DATA_DIR):
    os.chdir(DATA_DIR)
    print(f"Successfully connected! Current working directory: {os.getcwd()}")
else:
    print(f"Error: The folder '{DATA_DIR}' could not be found.")
    print("Make sure to add a shortcut of the 'data' folder to your 'My Drive'.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Successfully connected! Current working directory: /content/drive/.shortcut-targets-by-id/1_ib6SYLLQ6Asjybns0GSlgBDwFQrnmkj/data

In [ ]:
# Load all datasets
bradentonFL = pd.read_csv("cleaned/bradentonFL_tempData_cleaned.csv")
floridaCyanotoxins = pd.read_csv("cleaned/florida_cyanotoxins_2015-01-01_to_2026-06-17_cleaned.csv")
habsos = pd.read_csv("cleaned/habsos_cellcounts_cleaned.csv")
motemarine = pd.read_csv("cleaned/MoteMarine_BottomTemp_cleaned.csv")
nutrientsFL = pd.read_csv("cleaned/NutrientsFL_2006_2025_cleaned.csv")
#sarasota = pd.read_csv("Sarasota_Wind&Temp_cleaned.csv")

/tmp/ipykernel_3353/2583114628.py:3: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  floridaCyanotoxins = pd.read_csv("cleaned/florida_cyanotoxins_2015-01-01_to_2026-06-17_cleaned.csv")

bradentonFL

In [ ]:
bradentonFL.head(25)

    coop_id  year  month  day  precipitation  max_temp  min_temp
0     80945  2015      1    1           0.00      74.0      60.0
1     80945  2015      1    2           0.00      78.0      64.0
2     80945  2015      1    3           0.00      85.0      70.0
3     80945  2015      1    4           0.00      83.0      69.0
4     80945  2015      1    5           0.00      75.0      61.0
5     80945  2015      1    6           0.00      78.0      56.0
6     80945  2015      1    7           0.00      66.0      50.0
7     80945  2015      1    8           0.00      61.0      40.0
8     80945  2015      1    9           0.00      59.0      48.0
9     80945  2015      1   10           0.00      65.0      45.0
10    80945  2015      1   11           0.00      81.0      52.0
11    80945  2015      1   12           0.34      78.0      64.0
12    80945  2015      1   13           0.00      78.0      62.0
13    80945  2015      1   14           0.00      67.0      60.0
14    80945  2015      1   15           0.00      62.0      55.0
15    80945  2015      1   16           0.00      65.0      51.0
16    80945  2015      1   17           0.00      74.0      47.0
17    80945  2015      1   18           0.00      74.0      47.0
18    80945  2015      1   19           0.00      74.0      47.0
19    80945  2015      1   20           0.00      71.0      52.0
20    80945  2015      1   21           0.00      78.0      53.0
21    80945  2015      1   22           0.00      80.0      60.0
22    80945  2015      1   23           1.70      80.0      64.0
23    80945  2015      1   24           0.64      71.0      52.0
24    80945  2015      1   25           0.00      65.0      46.0

In [ ]:
# Combine the year, month, and day columns into one datetime column
bradentonFL["date"] = pd.to_datetime(bradentonFL[["year", "month", "day"]])

In [ ]:
# Calculate the average daily temperature
bradentonFL["avg_temp"] = (bradentonFL["max_temp"] + bradentonFL["min_temp"]) / 2

In [ ]:
# Calculate the difference between the maximum and minimum temperatures
bradentonFL["temp_range"] = bradentonFL["max_temp"] - bradentonFL["min_temp"]

In [ ]:
# Create an interaction between maximum and minimum temperature
bradentonFL["temp_interaction"] = bradentonFL["max_temp"] * bradentonFL["min_temp"]

In [ ]:
# Create a binary feature indicating whether any precipitation occurred
bradentonFL["rained"] = (bradentonFL["precipitation"] > 0).astype(int)

In [ ]:
# Convert the weather station ID into a categorical variable
bradentonFL["coop_id"] = bradentonFL["coop_id"].astype(str)

In [ ]:
# Divide average temperature into bins
bradentonFL["temp_bin"] = pd.cut(
    bradentonFL["avg_temp"],
    bins=[-np.inf, 50, 70, 85, np.inf],
    labels=["cold", "mild", "warm", "hot"]
)

In [ ]:
# coop_id: unnecessary if this is only one weather station
# day: redundant because date already contains the day
bradentonFL = bradentonFL.drop(columns=["coop_id", "day"], errors="ignore")

In [ ]:
bradentonFL.head(25)

,year,month,precipitation,max_temp,min_temp,date,avg_temp,temp_range,temp_interaction,rained,temp_bin
0,2015,1,0.00,74.0,60.0,2015-01-01,67.0,14.0,4440.0,0,mild
1,2015,1,0.00,78.0,64.0,2015-01-02,71.0,14.0,4992.0,0,warm
2,2015,1,0.00,85.0,70.0,2015-01-03,77.5,15.0,5950.0,0,warm
3,2015,1,0.00,83.0,69.0,2015-01-04,76.0,14.0,5727.0,0,warm
4,2015,1,0.00,75.0,61.0,2015-01-05,68.0,14.0,4575.0,0,mild
5,2015,1,0.00,78.0,56.0,2015-01-06,67.0,22.0,4368.0,0,mild
6,2015,1,0.00,66.0,50.0,2015-01-07,58.0,16.0,3300.0,0,mild
7,2015,1,0.00,61.0,40.0,2015-01-08,50.5,21.0,2440.0,0,mild
8,2015,1,0.00,59.0,48.0,2015-01-09,53.5,11.0,2832.0,0,mild
9,2015,1,0.00,65.0,45.0,2015-01-10,55.0,20.0,2925.0,0,mild
10,2015,1,0.00,81.0,52.0,2015-01-11,66.5,29.0,4212.0,0,mild
11,2015,1,0.34,78.0,64.0,2015-01-12,71.0,14.0,4992.0,1,warm
12,2015,1,0.00,78.0,62.0,2015-01-13,70.0,16.0,4836.0,0,mild
13,2015,1,0.00,67.0,60.0,2015-01-14,63.5,7.0,4020.0,0,mild
14,2015,1,0.00,62.0,55.0,2015-01-15,58.5,7.0,3410.0,0,mild
15,2015,1,0.00,65.0,51.0,2015-01-16,58.0,14.0,3315.0,0,mild
16,2015,1,0.00,74.0,47.0,2015-01-17,60.5,27.0,3478.0,0,mild
17,2015,1,0.00,74.0,47.0,2015-01-18,60.5,27.0,3478.0,0,mild
18,2015,1,0.00,74.0,47.0,2015-01-19,60.5,27.0,3478.0,0,mild
19,2015,1,0.00,71.0,52.0,2015-01-20,61.5,19.0,3692.0,0,mild
20,2015,1,0.00,78.0,53.0,2015-01-21,65.5,25.0,4134.0,0,mild
21,2015,1,0.00,80.0,60.0,2015-01-22,70.0,20.0,4800.0,0,mild
22,2015,1,1.70,80.0,64.0,2015-01-23,72.0,16.0,5120.0,1,warm
23,2015,1,0.64,71.0,52.0,2015-01-24,61.5,19.0,3692.0,1,mild
24,2015,1,0.00,65.0,46.0,2015-01-25,55.5,19.0,2990.0,0,mild

floridaCyanotoxins

In [ ]:
floridaCyanotoxins.head(25)

,Org_Identifier,Org_FormalName,Project_Identifier,Location_Identifier,Location_Name,Location_Type,Location_State,Location_HUCEightDigitCode,Location_HUCTwelveDigitCode,Location_Latitude,Location_Longitude,Activity_ActivityIdentifier,Activity_TypeCode,Activity_Media,Activity_MediaSubdivision,Activity_StartDate,Activity_StartTime,Activity_StartTimeZone,Activity_DepthHeightMeasure,Activity_DepthHeightMeasureUnit,SampleCollectionMethod_Name,Result_Characteristic,Result_SampleFraction,Result_MeasureIdentifier,Reslt_Measre,Result_MeasureUnit,Result_MeasureStatusIdentifier,Result_MeasureValueType,DataQuality_ResultComment,DetectionLimit_TypeA,DetectionLimit_MeasureA,DetectionLimit_MeasureUnitA,ResultAnalyticalMethod_Identifi,ResultAnalyticalMethod_Identi_1,ResultAnalyticalMethod_Name,LabInfo_AnalysisStartDate,LabInfo_AnalysisStartTime,LabInfo_AnalysisStartTimeZone,Result_DetectionLimitProfileDow,ProviderName,Result_CharacteristicGroup,Org_Type,LastChangeDate,ObjectId,Value_control
0,NARS_WQX,EPA National Aquatic Resources Survey (NARS),"[""NARS_NCCA2015""]",NARS_WQX-NCA_FL-10274,NCA_FL-10274,Ocean,Florida,NaN,NaN,29.304988,-81.057314,NARS_WQX-NCA_FL-10274:07012015:SR:AT,Sample-Routine,Water,Unknown,1.435720e+12,Unknown,Unknown,NaN,Unknown,NCCA Grab Sample,Microcystin,Unknown,STORET-937619122,0.193,ug/L,Final,Actual,Unknown,Minimum Reporting Level,0.263,ug/L,520011,ABRAXIS LLC,"Microcystins and Nodularins by Immunoassay, Mi...",Unknown,Unknown,Unknown,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",Federal/US Government,Fri Jan 31 08:59:46 GMT 2025,22434,A
1,NARS_WQX,EPA National Aquatic Resources Survey (NARS),"[""NARS_NCCA2015""]",NARS_WQX-NCA_FL-10305,NCA_FL-10305,Ocean,Florida,NaN,NaN,29.693174,-84.863160,NARS_WQX-NCA_FL-10305:07072015:SR:AT,Sample-Routine,Water,Unknown,1.436240e+12,Unknown,Unknown,NaN,Unknown,NCCA Grab Sample,Microcystin,Unknown,STORET-937619323,0.285,ug/L,Final,Actual,Unknown,Minimum Reporting Level,0.263,ug/L,520011,ABRAXIS LLC,"Microcystins and Nodularins by Immunoassay, Mi...",Unknown,Unknown,Unknown,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",Federal/US Government,Fri Jan 31 08:59:46 GMT 2025,21677,A
2,NARS_WQX,EPA National Aquatic Resources Survey (NARS),"[""NARS_NCCA2015""]",NARS_WQX-NCA_FL-10271,NCA_FL-10271,Ocean,Florida,NaN,NaN,27.459217,-80.319560,NARS_WQX-NCA_FL-10271:07142015:SR:AT,Sample-Routine,Water,Unknown,1.436850e+12,Unknown,Unknown,NaN,Unknown,NCCA Grab Sample,Microcystin,Unknown,STORET-937620031,0.184,ug/L,Final,Actual,Unknown,Minimum Reporting Level,0.263,ug/L,520011,ABRAXIS LLC,"Microcystins and Nodularins by Immunoassay, Mi...",Unknown,Unknown,Unknown,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",Federal/US Government,Fri Jan 31 08:59:46 GMT 2025,21683,A
3,NARS_WQX,EPA National Aquatic Resources Survey (NARS),"[""NARS_NCCA2015""]",NARS_WQX-NCA_FL-10245,NCA_FL-10245,Ocean,Florida,NaN,NaN,27.906991,-82.480553,NARS_WQX-NCA_FL-10245:07202015:SR:AT,Sample-Routine,Water,Unknown,1.437360e+12,Unknown,Unknown,NaN,Unknown,NCCA Grab Sample,Microcystin,Unknown,STORET-937620551,0.194,ug/L,Final,Actual,Unknown,Minimum Reporting Level,0.263,ug/L,520011,ABRAXIS LLC,"Microcystins and Nodularins by Immunoassay, Mi...",Unknown,Unknown,Unknown,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",Federal/US Government,Fri Jan 31 08:59:46 GMT 2025,26405,A
4,NARS_WQX,EPA National Aquatic Resources Survey (NARS),"[""NARS_NCCA2015""]",NARS_WQX-NCA_FL-10316,NCA_FL-10316,Ocean,Florida,NaN,NaN,30.236278,-85.831720,NARS_WQX-NCA_FL-10316:07212015:SR:AT,Sample-Routine,Water,Unknown,1.437450e+12,Unknown,Unknown,NaN,Unknown,NCCA Grab Sample,Microcystin,Unknown,STORET-937620623,0.184,ug/L,Final,Actual,Unknown,Minimum Reporting Level,0.263,ug/L,520011,ABRAXIS LLC,"Microcystins and Nodularins by Immunoassay, Mi...",Unknown,Unknown,Unknown,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",Federal/US Government,Fri Jan 31 08:59:46 GMT 2025,22775,A
5,21FLSFWM_WQX,South Florida Water Management District,"[""Y""]",21FLSFWM_WQX-10296,KISSR0.0,Lake,Florida,3090201.0,3.090201e+10,27.141301,-80.846000,21FLSFWM_WQX-P81247-1,Sample-Routine,Water,Surface Water,1.468210e+12,7:16:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,STORET-969990406,0.400,ug/L,Final,Actual,**I**,Practical Quantitation Limit,0.800,ug/L,SFWMD 3170,21FLSFWM_WQX,SFWMD 3170,7/14/2016,0001-01-01 12:09:00,EDT,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,27475,A
6,21FLSFWM_WQX,South Florida Water Management District,"[""Y""]",21FLSFWM_WQX-12877,LZ30,Lake,Florida,3090201.0,3.090201e+10,26.796971,-80.860095,21FLSFWM_WQX-P81251-2,Sample-Routine,Water,Surface Water,1.468300e+12,10:37:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,STORET-969980060,1.100,ug/L,Final,Actual,Unknown,Practical Quantitation Limit,0.800,ug/L,SFWMD 3170,21FLSFWM_WQX,SFWMD 3170,7/14/2016,0001-01-01 12:09:00,EDT,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,30512,A
7,21FLSFWM_WQX,South Florida Water Management District,"[""Y""]",21FLSFWM_WQX-10296,KISSR0.0,Lake,Florida,3090201.0,3.090201e+10,27.141301,-80.846000,21FLSFWM_WQX-P84348-1,Sample-Routine,Water,Surface Water,1.470110e+12,7:50:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,STORET-969996146,1.700,ug/L,Final,Actual,Unknown,Practical Quantitation Limit,0.800,ug/L,SFWMD 3170,21FLSFWM_WQX,SFWMD 3170,8/5/2016,0001-01-01 11:49:00,EDT,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,28322,A
8,21FLSFWM_WQX,South Florida Water Management District,"[""Y""]",21FLSFWM_WQX-12877,LZ30,Lake,Florida,3090201.0,3.090201e+10,26.796971,-80.860095,21FLSFWM_WQX-P84349-2,Sample-Routine,Water,Surface Water,1.470200e+12,9:07:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,STORET-970002377,0.200,ug/L,Final,Actual,**U**,Practical Quantitation Limit,0.800,ug/L,SFWMD 3170,21FLSFWM_WQX,SFWMD 3170,8/5/2016,0001-01-01 11:49:00,EDT,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,27659,A
9,21FLSFWM_WQX,South Florida Water Management District,"[""Y""]",21FLSFWM_WQX-10296,KISSR0.0,Lake,Florida,3090201.0,3.090201e+10,27.141301,-80.846000,21FLSFWM_WQX-P84302-2,Sample-Routine,Water,Surface Water,1.473130e+12,7:50:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,STORET-969965987,0.570,ug/L,Final,Actual,**I**,Practical Quantitation Limit,0.800,ug/L,SFWMD 3170,21FLSFWM_WQX,SFWMD 3170,9/12/2016,0001-01-01 12:10:00,EDT,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,30034,A
10,21FLSFWM_WQX,South Florida Water Management District,"[""Y""]",21FLSFWM_WQX-12877,LZ30,Lake,Florida,3090201.0,3.090201e+10,26.796971,-80.860095,21FLSFWM_WQX-P84329-2,Sample-Routine,Water,Surface Water,1.473220e+12,10:01:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,STORET-970004840,1.900,ug/L,Final,Actual,Unknown,Practical Quantitation Limit,0.800,ug/L,SFWMD 3170,21FLSFWM_WQX,SFWMD 3170,9/12/2016,0001-01-01 12:10:00,EDT,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,29939,A
11,21FLSFWM_WQX,South Florida Water Management District,"[""Y""]",21FLSFWM_WQX-10296,KISSR0.0,Lake,Florida,3090201.0,3.090201e+10,27.141301,-80.846000,21FLSFWM_WQX-P85385-1,Sample-Routine,Water,Surface Water,1.476760e+12,10:58:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,STORET-970003468,0.200,ug/L,Final,Actual,**U**,Practical Quantitation Limit,0.800,ug/L,SFWMD 3170,21FLSFWM_WQX,SFWMD 3170,10/24/2016,0001-01-01 12:32:00,EDT,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,28092,A
12,21FLSFWM_WQX,South Florida Water Management District,"[""Y""]",21FLSFWM_WQX-12877,LZ30,Lake,Florida,3090201.0,3.090201e+10,26.796971,-80.860095,21FLSFWM_WQX-P85386-2,Sample-Routine,Water,Surface Water,1.476850e+12,9:37:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,STORET-970008598,0.200,ug/L,Final,Actual,**U**,Practical Quantitation Limit,0.800,ug/L,SFWMD 3170,21FLSFWM_WQX,SFWMD 3170,10/24/2016,0001-01-01 12:32:00,EDT,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,28753,A
13,21FLSFWM_WQX,South Florida Water Management District,"[""Y""]",21FLSFWM_WQX-10296,KISSR0.0,Lake,Florida,3090201.0,3.090201e+10,27.141301,-80.846000,21FLSFWM_WQX-P85662-1,Sample-Routine,Water,Surface Water,1.477970e+12,11:55:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,STORET-969992475,0.200,ug/L,Final,Actual,**UJ**Precision or accuracy criteria not met,Practical Quantitation Limit,0.800,ug/L,SFWMD 3170,21FLSFWM_WQX,SFWMD 3170,11/7/2016,0001-01-01 12:15:00,EDT,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,28259,A
14,21FLSFWM_WQX,South Florida Water Management District,"[""Y""]",21FLSFWM_WQX-12877,LZ30,Lake,Florida,3090201.0,3.090201e+10,26.796971,-80.860095,21FLSFWM_WQX-P85663-2,Sample-Routine,Water,Surface Water,1.478060e+12,10:09:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,STORET-970014695,0.320,ug/L,Final,Actual,**IJ**Precision or accuracy criteria not met,Practical Quantitation Limit,0.800,ug/L,SFWMD 3170,21FLSFWM_WQX,SFWMD 3170,11/7/2016,0001-01-01 12:15:00,EDT,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,29136,A
15,21FLSFWM_WQX,South Florida Water Management District,"[""Y""]",21FLSFWM_WQX-12877,LZ30,Lake,Florida,3090201.0,3.090201e+10,26.796971,-80.860095,21FLSFWM_WQX-P85413-2,Sample-Routine,Water,Surface Water,1.481000e+12,9:16:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,STORET-970014646,0.200,ug/L,Final,Actual,**U**,Practical Quantitation Limit,0.800,ug/L,SFWMD 3170,21FLSFWM_WQX,SFWMD 3170,12/12/2016,0001-01-01 12:23:00,EDT,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,31201,A
16,21FLSFWM_WQX,South Florida Water Management District,"[""Y""]",21FLSFWM_WQX-10296,KISSR0.0,Lake,Florida,3090201.0,3.090201e+10,27.141301,-80.846000,21FLSFWM_WQX-P85403-2,Sample-Routine,Water,Surface Water,1.481090e+12,8:19:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,STORET-969978415,0.200,ug/L,Final,Actual,**U**,Practical Quantitation Limit,0.800,ug/L,SFWMD 3170,21FLSFWM_WQX,SFWMD 3170,12/12/2016,0001-01-01 12:23:00,EDT,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,29420,A
17,21FLSFWM_WQX,South Florida Water Management District,"[""Y""]",21FLSFWM_WQX-10296,KISSR0.0,Lake,Florida,3090201.0,3.090201e+10,27.141301,-80.846000,21FLSFWM_WQX-P87115-1,Sample-Routine,Water,Surface Water,1.483940e+12,7:41:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,STORET-969995098,0.200,ug/L,Final,Actual,**U**,Practical Quantitation Limit,0.800,ug/L,SFWMD 3170,21FLSFWM_WQX,SFWMD 3170,1/12/2017,0001-01-01 11:58:00,EDT,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,31738,A
18,21FLSFWM_WQX,South Florida Water Management District,"[""Y""]",21FLSFWM_WQX-12877,LZ30,Lake,Florida,3090201.0,3.090201e+10,26.796971,-80.860095,21FLSFWM_WQX-P87117-2,Sample-Routine,Water,Surface Water,1.484020e+12,11:46:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,STORET-969988364,0.200,ug/L,Final,Actual,**U**,Practical Quantitation Limit,0.800,ug/L,SFWMD 3170,21FLSFWM_WQX,SFWMD 3170,1/12/2017,0001-01-01 11:58:00,EDT,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,35879,A
19,21FLSFWM_WQX,South Florida Water Management District,"[""Y""]",21FLSFWM_WQX-10296,KISSR0.0,Lake,Florida,3090201.0,3.090201e+10,27.141301,-80.846000,21FLSFWM_WQX-P87116-1,Sample-Routine,Water,Surface Water,1.486440e+12,8:43:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,STORET-969953028,0.200,ug/L,Final,Actual,**U**,Practical Quantitation Limit,0.800,ug/L,SFWMD 3170,21FLSFWM_WQX,SFWMD 3170,2/13/2017,0001-01-01 11:32:00,EDT,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,42794,A
20,21FLSFWM_WQX,South Florida Water Management District,"[""Y""]",21FLSFWM_WQX-12877,LZ30,Lake,Florida,3090201.0,3.090201e+10,26.796971,-80.860095,21FLSFWM_WQX-P87118-2,Sample-Routine,Water,Surface Water,1.486530e+12,8:27:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,STORET-969988233,0.200,ug/L,Final,Actual,**U**,Practical Quantitation Limit,0.800,ug/L,SFWMD 3170,21FLSFWM_WQX,SFWMD 3170,2/13/2017,0001-01-01 11:32:00,EDT,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,32802,A
21,21FLWQA_WQX,FDEP Watershed Assessment Section (WAS),"[""BLOOM-RESP""]",21FLWQA_WQX-BLOOM535,Pahokee Marina,Lake,Florida,3090201.0,3.090201e+10,26.825042,-80.668021,21FLWQA_WQX-PAHOKEE MARINA-03/21/17,Sample-Routine,Water,Surface Water,1.490070e+12,14:20:00,EST,0.1,m,Direct Grab,Microcystin RR,Total,STORET-929418069,1.000,ug/L,Final,Actual,**U**Microcystin LF = 1.0 U ug/L and microcyst...,Practical Quantitation Limit,4.000,ug/L,8321,USEPA,Non-Volatile Compounds by HPLC,3/27/2017,0001-01-01 20:30:00,EST,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,32504,A
22,21FLWQA_WQX,FDEP Watershed Assessment Section (WAS),"[""BLOOM-RESP""]",21FLWQA_WQX-BLOOM535,Pahokee Marina,Lake,Florida,3090201.0,3.090201e+10,26.825042,-80.668021,21FLWQA_WQX-PAHOKEE MARINA-03/21/17,Sample-Routine,Water,Surface Water,1.490070e+12,14:20:00,EST,0.1,m,Direct Grab,Microcystin LA,Total,STORET-929418070,4.200,ug/L,Final,Actual,Microcystin LF = 1.0 U ug/L and microcystin LY...,Practical Quantitation Limit,4.000,ug/L,8321,USEPA,Non-Volatile Compounds by HPLC,3/27/2017,0001-01-01 20:30:00,EST,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,39174,A
23,21FLWQA_WQX,FDEP Watershed Assessment Section (WAS),"[""BLOOM-RESP""]",21FLWQA_WQX-BLOOM535,Pahokee Marina,Lake,Florida,3090201.0,3.090201e+10,26.825042,-80.668021,21FLWQA_WQX-PAHOKEE MARINA-03/21/17,Sample-Routine,Water,Surface Water,1.490070e+12,14:20:00,EST,0.1,m,Direct Grab,Microcystin LR,Total,STORET-929418062,27.000,ug/L,Final,Actual,Microcystin LF = 1.0 U ug/L and microcystin LY...,Practical Quantitation Limit,4.000,ug/L,8321,USEPA,Non-Volatile Compounds by HPLC,3/27/2017,0001-01-01 20:30:00,EST,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,42089,A
24,21FLWQA_WQX,FDEP Watershed Assessment Section (WAS),"[""BLOOM-RESP""]",21FLWQA_WQX-BLOOM535,Pahokee Marina,Lake,Florida,3090201.0,3.090201e+10,26.825042,-80.668021,21FLWQA_WQX-PAHOKEE MARINA-03/21/17,Sample-Routine,Water,Surface Water,1.490070e+12,14:20:00,EST,0.1,m,Direct Grab,Microcystin YR,Total,STORET-929418071,1.000,ug/L,Final,Actual,**U**Microcystin LF = 1.0 U ug/L and microcyst...,Practical Quantitation Limit,4.000,ug/L,8321,USEPA,Non-Volatile Compounds by HPLC,3/27/2017,0001-01-01 20:30:00,EST,https://www.waterqualitydata.us/data/providers...,STORET,"Cyanotoxins, Phytotoxins",State/US Government,Fri Jan 31 08:59:46 GMT 2025,44606,A

In [ ]:
# Create a binary indicator for whether the sampling location is a lake
floridaCyanotoxins["is_lake"] = (floridaCyanotoxins["Location_Type"] == "Lake").astype(int)

In [ ]:
# Convert the analysis start date into a datetime value
floridaCyanotoxins["LabInfo_AnalysisStartDate"] = pd.to_datetime(floridaCyanotoxins["LabInfo_AnalysisStartDate"], errors="coerce")

/tmp/ipykernel_3353/262050044.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  floridaCyanotoxins["LabInfo_AnalysisStartDate"] = pd.to_datetime(floridaCyanotoxins["LabInfo_AnalysisStartDate"], errors="coerce")

In [ ]:
# Extract the year from the sample date
floridaCyanotoxins["year"] = (
    floridaCyanotoxins["LabInfo_AnalysisStartDate"].dt.year
)

In [ ]:
# Extract the month from the sample date
floridaCyanotoxins["month"] = (
    floridaCyanotoxins["LabInfo_AnalysisStartDate"].dt.month
)

In [ ]:
# Extract the day of the year to represent seasonal timing
floridaCyanotoxins["day_of_year"] = (
    floridaCyanotoxins["LabInfo_AnalysisStartDate"].dt.dayofyear
)

In [ ]:
# Create an interaction between latitude and longitude
floridaCyanotoxins["lat_lon_interaction"] = (floridaCyanotoxins["Location_Latitude"] * floridaCyanotoxins["Location_Longitude"])

In [ ]:
# Divide latitude into geographic regions
floridaCyanotoxins["latitude_bin"] = pd.cut(floridaCyanotoxins["Location_Latitude"], bins=4, labels=["south", "south_central", "north_central", "north"])

In [ ]:
# One-hot encode the location type
floridaCyanotoxins = pd.get_dummies(floridaCyanotoxins, columns=["Location_Type"], prefix="location")

In [ ]:
# One-hot encode the organization type
floridaCyanotoxins = pd.get_dummies(floridaCyanotoxins, columns=["Org_Type"], prefix="org")

In [ ]:
# Columns that are primarily identifiers or metadata
# and are not expected to be useful as model features
drop_cols = [
    "ObjectId",
    "Activity_ActivityIdentifier",
    "Result_MeasureIdentifier",
    "Location_Identifier",
    "Project_Identifier",
    "Org_Identifier",
    "LastChangeDate",
    "DataQuality_ResultComment",
    "ResultAnalyticalMethod_Identifi",
    "ResultAnalyticalMethod_Identi_1",
    "ResultAnalyticalMethod_Name",
    "LabInfo_AnalysisStartDate",
    "LabInfo_AnalysisStartTime",
    "LabInfo_AnalysisStartTimeZone",
    "Result_DetectionLimitProfileDow",
    "Org_FormalName",
    "Location_Name",
    "Location_HUCEightDigitCode",
    "Location_HUCTwelveDigitCode"
]

# Remove the unnecessary columns
floridaCyanotoxins = floridaCyanotoxins.drop(
    columns=drop_cols,
    errors="ignore"
)

In [ ]:
floridaCyanotoxins.head(25)

,Location_State,Location_Latitude,Location_Longitude,Activity_TypeCode,Activity_Media,Activity_MediaSubdivision,Activity_StartDate,Activity_StartTime,Activity_StartTimeZone,Activity_DepthHeightMeasure,Activity_DepthHeightMeasureUnit,SampleCollectionMethod_Name,Result_Characteristic,Result_SampleFraction,Reslt_Measre,Result_MeasureUnit,Result_MeasureStatusIdentifier,Result_MeasureValueType,DetectionLimit_TypeA,DetectionLimit_MeasureA,DetectionLimit_MeasureUnitA,ProviderName,Result_CharacteristicGroup,Value_control,is_lake,year,month,day_of_year,lat_lon_interaction,latitude_bin,location_Canal Drainage,location_Canal Transport,location_Channelized Stream,location_Estuary,location_Lake,location_Ocean,location_Other-Surface Water,location_Reservoir,location_River/Stream,location_Spring,location_Wetland Undifferentiated,org_*State Government US,org_Federal/US Government,org_State/US Government
0,Florida,29.304988,-81.057314,Sample-Routine,Water,Unknown,1.435720e+12,Unknown,Unknown,NaN,Unknown,NCCA Grab Sample,Microcystin,Unknown,0.193,ug/L,Final,Actual,Minimum Reporting Level,0.263,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,0,NaN,NaN,NaN,-2375.383621,north_central,False,False,False,False,False,True,False,False,False,False,False,False,True,False
1,Florida,29.693174,-84.863160,Sample-Routine,Water,Unknown,1.436240e+12,Unknown,Unknown,NaN,Unknown,NCCA Grab Sample,Microcystin,Unknown,0.285,ug/L,Final,Actual,Minimum Reporting Level,0.263,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,0,NaN,NaN,NaN,-2519.856568,north,False,False,False,False,False,True,False,False,False,False,False,False,True,False
2,Florida,27.459217,-80.319560,Sample-Routine,Water,Unknown,1.436850e+12,Unknown,Unknown,NaN,Unknown,NCCA Grab Sample,Microcystin,Unknown,0.184,ug/L,Final,Actual,Minimum Reporting Level,0.263,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,0,NaN,NaN,NaN,-2205.512221,south_central,False,False,False,False,False,True,False,False,False,False,False,False,True,False
3,Florida,27.906991,-82.480553,Sample-Routine,Water,Unknown,1.437360e+12,Unknown,Unknown,NaN,Unknown,NCCA Grab Sample,Microcystin,Unknown,0.194,ug/L,Final,Actual,Minimum Reporting Level,0.263,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,0,NaN,NaN,NaN,-2301.784061,south_central,False,False,False,False,False,True,False,False,False,False,False,False,True,False
4,Florida,30.236278,-85.831720,Sample-Routine,Water,Unknown,1.437450e+12,Unknown,Unknown,NaN,Unknown,NCCA Grab Sample,Microcystin,Unknown,0.184,ug/L,Final,Actual,Minimum Reporting Level,0.263,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,0,NaN,NaN,NaN,-2595.231698,north,False,False,False,False,False,True,False,False,False,False,False,False,True,False
5,Florida,27.141301,-80.846000,Sample-Routine,Water,Surface Water,1.468210e+12,7:16:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,0.400,ug/L,Final,Actual,Practical Quantitation Limit,0.800,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2016.0,7.0,196.0,-2194.265615,south_central,False,False,False,False,True,False,False,False,False,False,False,False,False,True
6,Florida,26.796971,-80.860095,Sample-Routine,Water,Surface Water,1.468300e+12,10:37:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,1.100,ug/L,Final,Actual,Practical Quantitation Limit,0.800,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2016.0,7.0,196.0,-2166.805645,south,False,False,False,False,True,False,False,False,False,False,False,False,False,True
7,Florida,27.141301,-80.846000,Sample-Routine,Water,Surface Water,1.470110e+12,7:50:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,1.700,ug/L,Final,Actual,Practical Quantitation Limit,0.800,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2016.0,8.0,218.0,-2194.265615,south_central,False,False,False,False,True,False,False,False,False,False,False,False,False,True
8,Florida,26.796971,-80.860095,Sample-Routine,Water,Surface Water,1.470200e+12,9:07:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,0.200,ug/L,Final,Actual,Practical Quantitation Limit,0.800,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2016.0,8.0,218.0,-2166.805645,south,False,False,False,False,True,False,False,False,False,False,False,False,False,True
9,Florida,27.141301,-80.846000,Sample-Routine,Water,Surface Water,1.473130e+12,7:50:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,0.570,ug/L,Final,Actual,Practical Quantitation Limit,0.800,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2016.0,9.0,256.0,-2194.265615,south_central,False,False,False,False,True,False,False,False,False,False,False,False,False,True
10,Florida,26.796971,-80.860095,Sample-Routine,Water,Surface Water,1.473220e+12,10:01:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,1.900,ug/L,Final,Actual,Practical Quantitation Limit,0.800,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2016.0,9.0,256.0,-2166.805645,south,False,False,False,False,True,False,False,False,False,False,False,False,False,True
11,Florida,27.141301,-80.846000,Sample-Routine,Water,Surface Water,1.476760e+12,10:58:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,0.200,ug/L,Final,Actual,Practical Quantitation Limit,0.800,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2016.0,10.0,298.0,-2194.265615,south_central,False,False,False,False,True,False,False,False,False,False,False,False,False,True
12,Florida,26.796971,-80.860095,Sample-Routine,Water,Surface Water,1.476850e+12,9:37:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,0.200,ug/L,Final,Actual,Practical Quantitation Limit,0.800,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2016.0,10.0,298.0,-2166.805645,south,False,False,False,False,True,False,False,False,False,False,False,False,False,True
13,Florida,27.141301,-80.846000,Sample-Routine,Water,Surface Water,1.477970e+12,11:55:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,0.200,ug/L,Final,Actual,Practical Quantitation Limit,0.800,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2016.0,11.0,312.0,-2194.265615,south_central,False,False,False,False,True,False,False,False,False,False,False,False,False,True
14,Florida,26.796971,-80.860095,Sample-Routine,Water,Surface Water,1.478060e+12,10:09:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,0.320,ug/L,Final,Actual,Practical Quantitation Limit,0.800,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2016.0,11.0,312.0,-2166.805645,south,False,False,False,False,True,False,False,False,False,False,False,False,False,True
15,Florida,26.796971,-80.860095,Sample-Routine,Water,Surface Water,1.481000e+12,9:16:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,0.200,ug/L,Final,Actual,Practical Quantitation Limit,0.800,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2016.0,12.0,347.0,-2166.805645,south,False,False,False,False,True,False,False,False,False,False,False,False,False,True
16,Florida,27.141301,-80.846000,Sample-Routine,Water,Surface Water,1.481090e+12,8:19:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,0.200,ug/L,Final,Actual,Practical Quantitation Limit,0.800,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2016.0,12.0,347.0,-2194.265615,south_central,False,False,False,False,True,False,False,False,False,False,False,False,False,True
17,Florida,27.141301,-80.846000,Sample-Routine,Water,Surface Water,1.483940e+12,7:41:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,0.200,ug/L,Final,Actual,Practical Quantitation Limit,0.800,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2017.0,1.0,12.0,-2194.265615,south_central,False,False,False,False,True,False,False,False,False,False,False,False,False,True
18,Florida,26.796971,-80.860095,Sample-Routine,Water,Surface Water,1.484020e+12,11:46:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,0.200,ug/L,Final,Actual,Practical Quantitation Limit,0.800,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2017.0,1.0,12.0,-2166.805645,south,False,False,False,False,True,False,False,False,False,False,False,False,False,True
19,Florida,27.141301,-80.846000,Sample-Routine,Water,Surface Water,1.486440e+12,8:43:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,0.200,ug/L,Final,Actual,Practical Quantitation Limit,0.800,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2017.0,2.0,44.0,-2194.265615,south_central,False,False,False,False,True,False,False,False,False,False,False,False,False,True
20,Florida,26.796971,-80.860095,Sample-Routine,Water,Surface Water,1.486530e+12,8:27:00,EDT,0.5,m,Intermediate Grab,Microcystins and nodularins,Total,0.200,ug/L,Final,Actual,Practical Quantitation Limit,0.800,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2017.0,2.0,44.0,-2166.805645,south,False,False,False,False,True,False,False,False,False,False,False,False,False,True
21,Florida,26.825042,-80.668021,Sample-Routine,Water,Surface Water,1.490070e+12,14:20:00,EST,0.1,m,Direct Grab,Microcystin RR,Total,1.000,ug/L,Final,Actual,Practical Quantitation Limit,4.000,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2017.0,3.0,86.0,-2163.923068,south,False,False,False,False,True,False,False,False,False,False,False,False,False,True
22,Florida,26.825042,-80.668021,Sample-Routine,Water,Surface Water,1.490070e+12,14:20:00,EST,0.1,m,Direct Grab,Microcystin LA,Total,4.200,ug/L,Final,Actual,Practical Quantitation Limit,4.000,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2017.0,3.0,86.0,-2163.923068,south,False,False,False,False,True,False,False,False,False,False,False,False,False,True
23,Florida,26.825042,-80.668021,Sample-Routine,Water,Surface Water,1.490070e+12,14:20:00,EST,0.1,m,Direct Grab,Microcystin LR,Total,27.000,ug/L,Final,Actual,Practical Quantitation Limit,4.000,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2017.0,3.0,86.0,-2163.923068,south,False,False,False,False,True,False,False,False,False,False,False,False,False,True
24,Florida,26.825042,-80.668021,Sample-Routine,Water,Surface Water,1.490070e+12,14:20:00,EST,0.1,m,Direct Grab,Microcystin YR,Total,1.000,ug/L,Final,Actual,Practical Quantitation Limit,4.000,ug/L,STORET,"Cyanotoxins, Phytotoxins",A,1,2017.0,3.0,86.0,-2163.923068,south,False,False,False,False,True,False,False,False,False,False,False,False,False,True

habsos

In [ ]:
pd.set_option("display.max_columns", None)
habsos.head(25)

,OBJECTID,DESCRIPTION,LATITUDE,LONGITUDE,STATE_ID,SAMPLE_DATE,SAMPLE_DEPTH,GENUS,SPECIES,CATEGORY,CELLCOUNT,CELLCOUNT_UNIT,CELLCOUNT_QA,SALINITY,SALINITY_UNIT,SALINITY_QA,WATER_TEMP,WATER_TEMP_UNIT,WATER_TEMP_QA,WIND_DIR_QA,WIND_SPEED_QA,QA_COMMENT,LOG_CELLCOUNT
0,68622,Bahia Honda State Park; Atlantic Side,24.0000,-81.0000,FL,2006-02-09 00:00:00,0.5,Karenia,brevis,not observed,0.0,cells/L,1,37.62,ppt,1,14.50,deg. C,1,9,9,Missing/invalid time of day,0.000000
1,31257,off Key West,24.2010,-82.2060,FL,1991-01-14 00:00:00,0.5,Karenia,brevis,not observed,0.0,cells/L,1,NaN,Unknown,9,24.80,deg. C,1,9,9,Missing/invalid time of day,0.000000
2,31116,off Key West,24.2290,-81.9860,FL,1990-11-28 11:11:00,0.5,Karenia,brevis,not observed,0.0,cells/L,1,NaN,Unknown,9,26.00,deg. C,1,9,9,Unknown,0.000000
3,30806,off Key West,24.2510,-81.9522,FL,1990-07-20 00:00:00,0.5,Karenia,brevis,not observed,0.0,cells/L,1,NaN,Unknown,9,29.00,deg. C,1,9,9,Missing/invalid time of day,0.000000
4,31117,off lower Keys,24.2510,-81.5000,FL,1990-11-28 13:28:00,0.5,Karenia,brevis,not observed,0.0,cells/L,1,NaN,Unknown,9,25.00,deg. C,1,9,9,Unknown,0.000000
5,31118,off Tortugas,24.2520,-82.9750,FL,1990-11-28 06:55:00,0.5,Karenia,brevis,not observed,0.0,cells/L,1,NaN,Unknown,9,26.70,deg. C,1,9,9,Unknown,0.000000
6,31926,off Tortugas,24.2700,-82.5000,FL,1991-08-18 08:00:00,0.5,Karenia,brevis,not observed,0.0,cells/L,1,NaN,Unknown,9,31.10,deg. C,1,9,9,Unknown,0.000000
7,31925,off Key West; Atlantic,24.2700,-82.1200,FL,1991-08-18 09:30:00,0.5,Karenia,brevis,very low,3000.0,cells/L,1,NaN,Unknown,9,30.10,deg. C,1,9,9,Unknown,8.006701
8,31927,off Keys,24.2800,-81.8300,FL,1991-08-18 10:45:00,0.5,Karenia,brevis,not observed,0.0,cells/L,1,NaN,Unknown,9,31.10,deg. C,1,9,9,Unknown,0.000000
9,30912,off Key West,24.3090,-82.0000,FL,1990-08-25 07:40:00,0.5,Karenia,brevis,very low,5000.0,cells/L,1,NaN,Unknown,9,30.40,deg. C,1,9,9,Unknown,8.517393
10,494908,off Key West,24.3200,-82.2800,FL,1991-03-17 00:00:00,0.5,Karenia,brevis,very low,2.0,cells/L,1,NaN,Unknown,9,23.30,deg. C,1,9,9,Missing/invalid time of day,1.098612
11,75343,Near Key West,24.3240,-81.4251,FL,2007-02-23 16:48:00,0.2,Karenia,brevis,not observed,0.0,cells/L,1,34.60,ppt,1,20.40,deg. C,1,9,9,Unknown,0.000000
12,75344,Near Key West,24.3240,-81.4251,FL,2007-02-23 16:48:00,4.0,Karenia,brevis,not observed,0.0,cells/L,1,34.70,ppt,1,20.40,deg. C,1,9,9,Unknown,0.000000
13,30807,off Tortugas,24.3280,-82.8250,FL,1990-07-20 00:00:00,0.5,Karenia,brevis,very low,4000.0,cells/L,1,NaN,Unknown,9,29.10,deg. C,1,9,9,Missing/invalid time of day,8.294300
14,493678,off Tortugas,24.3300,-83.3200,FL,1991-02-20 00:00:00,0.5,Karenia,brevis,very low,4.0,cells/L,1,NaN,Unknown,9,23.30,deg. C,1,9,9,Missing/invalid time of day,1.609438
15,494909,off Tortugas,24.3300,-83.1700,FL,1991-03-17 00:00:00,0.5,Karenia,brevis,very low,2.0,cells/L,1,NaN,Unknown,9,23.00,deg. C,1,9,9,Missing/invalid time of day,1.098612
16,493677,off Key West,24.3300,-82.2000,FL,1991-02-20 00:00:00,0.5,Karenia,brevis,very low,1.0,cells/L,1,NaN,Unknown,9,23.50,deg. C,1,9,9,Missing/invalid time of day,0.693147
17,26838,Isaac Shoal; ~10 mi S of,24.3333,-82.5000,FL,1983-10-18 00:00:00,0.5,Karenia,brevis,not observed,0.0,cells/L,1,34.00,ppt,1,28.50,deg. C,1,9,9,Missing/invalid time of day,0.000000
18,26837,Marquesas; FL Keys; South of,24.3333,-82.0000,FL,1983-10-18 12:00:00,0.5,Karenia,brevis,not observed,0.0,cells/L,1,34.00,ppt,1,28.60,deg. C,1,9,9,Unknown,0.000000
19,67613,WS 4,24.3344,-81.7196,FL,2005-12-02 17:03:00,0.5,Karenia,brevis,not observed,0.0,cells/L,1,34.51,ppt,1,23.44,deg. C,1,9,9,Unknown,0.000000
20,27166,Tortugas and Key West; ~36 mi SW,24.3355,-82.5013,FL,1984-02-24 13:20:00,0.5,Karenia,brevis,not observed,0.0,cells/L,1,37.50,ppt,1,25.00,deg. C,1,9,9,Unknown,0.000000
21,31119,off middle Keys,24.3360,-80.9860,FL,1990-11-28 15:45:00,0.5,Karenia,brevis,not observed,0.0,cells/L,1,NaN,Unknown,9,27.00,deg. C,1,9,9,Unknown,0.000000
22,30808,off lower Keys,24.3545,-81.3231,FL,1990-07-20 00:00:00,0.5,Karenia,brevis,not observed,0.0,cells/L,1,NaN,Unknown,9,28.90,deg. C,1,9,9,Missing/invalid time of day,0.000000
23,30913,Between Key West and Tortugas,24.3570,-82.5000,FL,1990-08-25 09:53:00,0.5,Karenia,brevis,very low,2000.0,cells/L,1,NaN,Unknown,9,30.40,deg. C,1,9,9,Unknown,7.601402
24,31258,off lower keys; Atlantic,24.3570,-81.7850,FL,1991-01-14 00:00:00,0.5,Karenia,brevis,not observed,0.0,cells/L,1,NaN,Unknown,9,24.90,deg. C,1,9,9,Missing/invalid time of day,0.000000

In [ ]:
# Convert SAMPLE_DATE to datetime
habsos["SAMPLE_DATE"] = pd.to_datetime(habsos["SAMPLE_DATE"], errors="coerce")

In [ ]:
# Extract basic date features
habsos["year"] = habsos["SAMPLE_DATE"].dt.year
habsos["month"] = habsos["SAMPLE_DATE"].dt.month
habsos["day_of_year"] = habsos["SAMPLE_DATE"].dt.dayofyear

In [ ]:
drop_cols = [
    "OBJECTID",
    "DESCRIPTION",
    "STATE_ID",
    "GENUS",
    "SPECIES",
    "CELLCOUNT_UNIT",
    "SALINITY_UNIT",
    "WATER_TEMP_UNIT",
    "CELLCOUNT_QA",
    "SALINITY_QA",
    "WATER_TEMP_QA",
    "WIND_DIR_QA",
    "WIND_SPEED_QA",
    "QA_COMMENT",
    "CATEGORY",
    "LOG_CELLCOUNT"
]

habsos = habsos.drop(columns=drop_cols, errors="ignore")

In [ ]:
habsos.head(25)

,LATITUDE,LONGITUDE,SAMPLE_DATE,SAMPLE_DEPTH,CELLCOUNT,SALINITY,WATER_TEMP,year,month,day_of_year
0,24.0000,-81.0000,2006-02-09 00:00:00,0.5,0.0,37.62,14.50,2006,2,40
1,24.2010,-82.2060,1991-01-14 00:00:00,0.5,0.0,NaN,24.80,1991,1,14
2,24.2290,-81.9860,1990-11-28 11:11:00,0.5,0.0,NaN,26.00,1990,11,332
3,24.2510,-81.9522,1990-07-20 00:00:00,0.5,0.0,NaN,29.00,1990,7,201
4,24.2510,-81.5000,1990-11-28 13:28:00,0.5,0.0,NaN,25.00,1990,11,332
5,24.2520,-82.9750,1990-11-28 06:55:00,0.5,0.0,NaN,26.70,1990,11,332
6,24.2700,-82.5000,1991-08-18 08:00:00,0.5,0.0,NaN,31.10,1991,8,230
7,24.2700,-82.1200,1991-08-18 09:30:00,0.5,3000.0,NaN,30.10,1991,8,230
8,24.2800,-81.8300,1991-08-18 10:45:00,0.5,0.0,NaN,31.10,1991,8,230
9,24.3090,-82.0000,1990-08-25 07:40:00,0.5,5000.0,NaN,30.40,1990,8,237
10,24.3200,-82.2800,1991-03-17 00:00:00,0.5,2.0,NaN,23.30,1991,3,76
11,24.3240,-81.4251,2007-02-23 16:48:00,0.2,0.0,34.60,20.40,2007,2,54
12,24.3240,-81.4251,2007-02-23 16:48:00,4.0,0.0,34.70,20.40,2007,2,54
13,24.3280,-82.8250,1990-07-20 00:00:00,0.5,4000.0,NaN,29.10,1990,7,201
14,24.3300,-83.3200,1991-02-20 00:00:00,0.5,4.0,NaN,23.30,1991,2,51
15,24.3300,-83.1700,1991-03-17 00:00:00,0.5,2.0,NaN,23.00,1991,3,76
16,24.3300,-82.2000,1991-02-20 00:00:00,0.5,1.0,NaN,23.50,1991,2,51
17,24.3333,-82.5000,1983-10-18 00:00:00,0.5,0.0,34.00,28.50,1983,10,291
18,24.3333,-82.0000,1983-10-18 12:00:00,0.5,0.0,34.00,28.60,1983,10,291
19,24.3344,-81.7196,2005-12-02 17:03:00,0.5,0.0,34.51,23.44,2005,12,336
20,24.3355,-82.5013,1984-02-24 13:20:00,0.5,0.0,37.50,25.00,1984,2,55
21,24.3360,-80.9860,1990-11-28 15:45:00,0.5,0.0,NaN,27.00,1990,11,332
22,24.3545,-81.3231,1990-07-20 00:00:00,0.5,0.0,NaN,28.90,1990,7,201
23,24.3570,-82.5000,1990-08-25 09:53:00,0.5,2000.0,NaN,30.40,1990,8,237
24,24.3570,-81.7850,1991-01-14 00:00:00,0.5,0.0,NaN,24.90,1991,1,14

In [ ]:
os.chdir(DATA_DIR+"/engineered")
bradentonFL.to_csv("bradentonFL_tempData_engineered.csv", index=False)
print("Saved cleaned dataset to bradentonFL_tempData_engineered.csv")
floridaCyanotoxins.to_csv("florida_cyanotoxins_2015-01-01_to_2026-06-17_engineered.csv", index=False)
print("Saved cleaned dataset to florida_cyanotoxins_2015-01-01_to_2026-06-17_engineered.csv")
habsos.to_csv("habsos_cellcounts_engineered.csv", index=False)
print("Saved cleaned dataset to habsos_cellcounts_engineered.csv")

Saved cleaned dataset to bradentonFL_tempData_engineered.csv
Saved cleaned dataset to florida_cyanotoxins_2015-01-01_to_2026-06-17_engineered.csv
Saved cleaned dataset to habsos_cellcounts_engineered.csv

Sarasota_Wind&Temp.csv

In [ ]:
if "wind_speed_of_gust_qc_agg" in sarasota.columns:
    sarasota = sarasota.drop(columns=["wind_speed_of_gust_qc_agg"])

In [ ]:
# Standardizing continuous weather measurements.

sarasota_numeric = [
    "air_pressure_at_mean_sea_level",
    "dew_point_temperature",
    "air_temperature",
    "visibility_in_air",
    "wind_speed_of_gust",
    "wind_speed"
]
sarasota_numeric = [c for c in sarasota_numeric if c in sarasota.columns]

sarasota_scaler = StandardScaler()
sarasota[sarasota_numeric] = sarasota_scaler.fit_transform(sarasota[sarasota_numeric])

Circular-encoding wind direction. 359 degrees and 1 degree are not very "close" numbers, but roughly the same degree. We split this part of the data into sine/cosine.

In [ ]:
if "wind_from_direction" in sarasota.columns:
    wind_rad = np.radians(sarasota["wind_from_direction"])
    sarasota["wind_dir_sin"] = np.sin(wind_rad)
    sarasota["wind_dir_cos"] = np.cos(wind_rad)
    sarasota = sarasota.drop(columns=["wind_from_direction"])

A raw timestamp string won't be useful for our model because it hides patterns relating to season that are important for what we are trying to accomplish. Month is cyclically encoded (similar to what was done with wind direction).

In [ ]:
if "time" in sarasota.columns:
    dt = pd.to_datetime(sarasota["time"], utc=True, errors="coerce")
    sarasota["month"] = dt.dt.month
    sarasota["month_sin"] = np.sin(2 * np.pi * sarasota["month"] / 12)
    sarasota["month_cos"] = np.cos(2 * np.pi * sarasota["month"] / 12)

MoteMarine_BottomTemp

Standardizing sea_water-temperature.

In [ ]:
mote_numeric = ["sea_water_temperature"]

motemarine[mote_numeric] = motemarine[mote_numeric].apply(pd.to_numeric, errors='coerce')
motemarine.dropna(subset=mote_numeric, inplace=True)

mote_scaler = StandardScaler()
motemarine[mote_numeric] = mote_scaler.fit_transform(motemarine[mote_numeric])

Similar to the Sarasota dataset, here we cyclically encode month from the timestamp. Seasonality is important for determining bloom risk. This keeps January and December "close" together.

In [ ]:
if "time" in motemarine.columns:
    dt = pd.to_datetime(motemarine["time"], utc=True, errors="coerce")
    motemarine["month"] = dt.dt.month
    motemarine["month_sin"] = np.sin(2 * np.pi * motemarine["month"] / 12)
    motemarine["month_cos"] = np.cos(2 * np.pi * motemarine["month"] / 12)

NutrientsFL_2006_2025.csv

DataSource/Actual_DataSource and StationID/Actual_StationID are redundant pairs.

In [ ]:
print("DataSource == Actual_DataSource:", (nutrientsFL["DataSource"] == nutrientsFL["Actual_DataSource"]).mean())
print("StationID == Actual_StationID:", (nutrientsFL["StationID"] == nutrientsFL["Actual_StationID"]).mean())

nutrients = nutrientsFL.drop(columns=["Actual_DataSource", "Actual_StationID"])

DataSource == Actual_DataSource: 1.0
StationID == Actual_StationID: 1.0

Characteristic and MDL_Unit have inconsistent capitalization across the same measurements. The text is normalized here.

In [ ]:
print("Characteristic categories before:", nutrients["Characteristic"].nunique())
print("MDL_Unit categories before:", nutrients["MDL_Unit"].nunique())

nutrients["Characteristic"] = nutrients["Characteristic"].str.strip().str.lower()
nutrients["MDL_Unit"] = nutrients["MDL_Unit"].str.strip().str.lower()

print("\nCharacteristic categories after:", nutrients["Characteristic"].nunique())
print("MDL_Unit categories after:", nutrients["MDL_Unit"].nunique())

Characteristic categories before: 21
MDL_Unit categories before: 16

Characteristic categories after: 18
MDL_Unit categories after: 14

Standardizing Activity_Depth and MDL.

In [ ]:
nutrients_numeric = ["Activity_Depth", "MDL"]

nutrients_scaler = StandardScaler()
nutrients[nutrients_numeric] = nutrients_scaler.fit_transform(nutrients[nutrients_numeric])

One-hot encoding the categorical columns.

In [ ]:
nutrients_categorical = [
    "Activity_Type",
    "RelativeDepth",
    "Activity_Depth_Unit",
    "Characteristic",
    "Result_Unit",
    "Value_Qualifier",
    "Sample_Fraction",
    "MDL_Unit"
]

encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
nutrients_encoded = encoder.fit_transform(nutrients[nutrients_categorical])
nutrients_encoded_columns = encoder.get_feature_names_out(nutrients_categorical)
nutrients_encoded_df = pd.DataFrame(
    nutrients_encoded,
    columns=nutrients_encoded_columns,
    index=nutrients.index
)

Cyclically encoding month for seasonality purposes.

In [ ]:
nutrients["Activity_Start_Date"] = pd.to_datetime(nutrients["Activity_Start_Date"], errors="coerce")
nutrients["month"] = nutrients["Activity_Start_Date"].dt.month
nutrients["month_sin"] = np.sin(2 * np.pi * nutrients["month"] / 12)
nutrients["month_cos"] = np.cos(2 * np.pi * nutrients["month"] / 12)

Isolating the relevant nutrient measurements.

In [ ]:
hab_relevant_characteristics = [
    "chlorophyll a, corrected for pheophytin",
    "nitrogen, nitrite (no2) + nitrate (no3) as n",
    "phosphorus as p",
    "phosphorus, phosphate (po4) as p"
]

hab_subset = nutrients[nutrients["Characteristic"].isin(hab_relevant_characteristics)]

nutrients_hab_wide = hab_subset.pivot_table(
    index=["StationID", "Activity_Start_Date"],
    columns="Characteristic",
    values="Result_Value",
    aggfunc="mean"
).reset_index()

nutrients_hab_wide.columns.name = None